{% set name = "scine-utilities-python" %}
{% set version = "5.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/qcscine/utilities/archive/refs/tags/{{ version }}.tar.gz
    sha256: a304c89d9a196fe304f38610dea6b066d74590c0d434e4bd09a9796340700465
    fn: {{ name }}.tar.gz
    patches:
      - skip_library_build.patch
  - url: https://github.com/qcscine/development-utils/archive/refs/tags/5.0.0.tar.gz
    sha256: bb2f161ed15811def85ca635924427356564a811779993123077f4ada048be84
    fn: dev.tar.gz
    folder: dev
    patches:
      - pybind11_pin.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - pkg-config
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - boost-cpp
    - eigen
    - gtest
    - gmock
    - lbfgspp
    - libblas
    - pip
    - pybind11
    - pybind11-abi
    - python
    - scine-core
    - scine-utilsos {{ version }}
    - yaml-cpp
  run:
    - numpy
    - python
    - scine-utilsos {{ version }}
    - scipy
    - yaml-cpp

test:
  imports:
    - scine_utilities
  source_files:
    - src/Utils/Python/Tests/
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest src/Utils/Python/Tests/

about:
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: |
    Contains functionality which is used in most SCINE modules (Python bindings).
  home: https://scine.ethz.ch/
  dev_url: https://github.com/qcscine/utilities

extra:
  recipe-maintainers:
    - awvwgk
